#include "../headers/globals.h"

ERR SUCCESS = { 0, "SUCCESS" };
ERR ERROR_ILLEGAL_INPUT   = { 0, "ERROR_ILLEGAL_INPUT" };
ERR ERROR_ILLEGAL_INPUT_EXCEEDS_BUFFER_LIMIT = { 2, "ERROR_ILLEGAL_INPUT_EXCEEDS_BUFFER_LIMIT" };
ERR ERROR_STACK_OVERFLOW   = { 3, "ERROR_STACK_OVERFLOW" };
ERR ERROR_STACK_UNDERFLOW  = { 4, "ERROR_STACK_UNDERFLOW" };
ERR ERROR_CANNOT_DIVIDE_BY_ZERO   = { 1, "ERROR_CANNOT_DIVIDE_BY_ZERO" };
