#include "../headers/globals.h"

ERR SUCCESS = { 0, ""};
ERR ERROR_ILLEGAL_INPUT   = { 0, "ERROR: ILLEGAL INPUT" };
ERR ERROR_ILLEGAL_INPUT_EXCEEDS_BUFFER_LIMIT = { 2, "ERROR: INPUT EXCEEDS BUFFER LIMIT" };
ERR ERROR_STACK_OVERFLOW   = { 3, "ERROR: STACK OVERFLOW" };
ERR ERROR_STACK_UNDERFLOW  = { 4, "ERROR: STACK UNDERFLOW" };
ERR ERROR_CANNOT_DIVIDE_BY_ZERO   = { 1, "ERROR: CANNOT DIVIDE BY ZERO" };
